---
version: '3.5'

networks:
  confluent:

services:
  zookeeper1:
    image: geerlingguy/docker-centos7-ansible
    privileged: true
    hostname: zookeeper1.confluent
    container_name: zookeeper1
    ports:
      - "2181:2181"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - confluent

  kafka-broker1:
    image: geerlingguy/docker-centos7-ansible
    hostname: kafka-broker1.confluent
    container_name: kafka-broker1
    privileged: true
    ports:
      - "9092:9092"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - confluent

  kafka-broker2:
    image: geerlingguy/docker-centos7-ansible
    hostname: kafka-broker2.confluent
    container_name: kafka-broker2
    privileged: true
    ports:
      - "9192:9092"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - confluent

  kafka-broker3:
    image: geerlingguy/docker-centos7-ansible
    hostname: kafka-broker3.confluent
    container_name: kafka-broker3
    privileged: true
    ports:
      - "9292:9092"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - confluent

  schema-registry1:
    image: geerlingguy/docker-centos7-ansible
    build: .
    hostname: schema-registry1.confluent
    container_name: schema-registry1
    privileged: true
    ports:
      - "8081:8081"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - confluent

  control-center1:
    image: geerlingguy/docker-centos7-ansible
    hostname: control-center1.confluent
    container_name: control-center1
    privileged: true
    ports:
      - "9021:9021"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - confluent

  ## Uncomment if you want below components
  # kafka-connect1:
  #   image: geerlingguy/docker-centos7-ansible
  #   hostname: kafka-connect1.confluent
  #   container_name: kafka-connect1
  #   privileged: true
  #   ports:
  #     - "8083:8083"
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   networks:
  #     - confluent
  #
  # ksql1:
  #   image: geerlingguy/docker-centos7-ansible
  #   hostname: ksql1.confluent
  #   container_name: ksql1
  #   privileged: true
  #   ports:
  #     - "8088:8088"
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   networks:
  #     - confluent
  #
  # kafka-rest1:
  #   image: geerlingguy/docker-centos7-ansible
  #   hostname: kafka-rest1:.confluent
  #   container_name: kafka-rest1:
  #   privileged: true
  #   ports:
  #     - "8082:8082"
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   networks:
  #     - confluent
