all:
  vars:
    ansible_connection: docker
    ansible_user: root
    ansible_become: true

    ssl_enabled: true

zookeeper:
  hosts:
    zookeeper1:

kafka_broker:
  hosts:
    kafka-broker1:
      broker_id: 1
    kafka-broker2:
      broker_id: 2
    kafka-broker3:
      broker_id: 3

schema_registry:
  hosts:
    schema-registry1:

# Uncomment below if you want to provision additional components. Must also uncomment in docker-compose.yml
# kafka_connect:
#   hosts:
#     kafka-connect1:
#
# kafka_rest:
#   hosts:
#     kafka-rest1:
#
# ksql:
#   hosts:
#     ksql1:

control_center:
  hosts:
    control-center1:
