version: '2'
services:

  web:
    image: ansible/awx:17.0.0
    container_name: awx_web
    depends_on:
      - redis
      - postgres
    ports:
      - "8052:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "$PWD/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "$PWD/environment.sh:/etc/tower/conf.d/environment.sh"
      - "$PWD/credentials.py:/etc/tower/conf.d/credentials.py"
      - "$PWD/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "$PWD/redis_socket:/var/run/redis/:rw"
    environment:
      http_proxy:
      https_proxy:
      no_proxy:

  task:
    image: ansible/awx:17.0.0
    container_name: awx_task
    depends_on:
      - redis
      - web
      - postgres
    command: /usr/bin/launch_awx_task.sh
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "$PWD/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "$PWD/environment.sh:/etc/tower/conf.d/environment.sh"
      - "$PWD/credentials.py:/etc/tower/conf.d/credentials.py"
      - "$PWD/redis_socket:/var/run/redis/:rw"
    environment:
      AWX_SKIP_MIGRATIONS: "1"
      http_proxy:
      https_proxy:
      no_proxy:
      SUPERVISOR_WEB_CONFIG_PATH: '/etc/supervisord.conf'

  redis:
    image: redis
    container_name: awx_redis
    restart: unless-stopped
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - "$PWD/redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - "$PWD/redis_socket:/var/run/redis/:rw"

  postgres:
    image: postgres:12
    container_name: awx_postgres
    restart: unless-stopped
    volumes:
      - "$PWD/pgdocker/12/data/:/var/lib/postgresql/data:Z"
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      http_proxy:
      https_proxy:
      no_proxy:

  zookeeper1:
    image: geerlingguy/docker-centos7-ansible
    privileged: true
    hostname: zookeeper1.confluent
    container_name: zookeeper1
    ports:
      - "2181:2181"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  kafka-broker1:
    image: geerlingguy/docker-centos7-ansible
    hostname: kafka-broker1.confluent
    container_name: kafka-broker1
    privileged: true
    ports:
      - "9092:9092"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  kafka-broker2:
    image: geerlingguy/docker-centos7-ansible
    hostname: kafka-broker2.confluent
    container_name: kafka-broker2
    privileged: true
    ports:
      - "9192:9092"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  kafka-broker3:
    image: geerlingguy/docker-centos7-ansible
    hostname: kafka-broker3.confluent
    container_name: kafka-broker3
    privileged: true
    ports:
      - "9292:9092"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  schema-registry1:
    image: geerlingguy/docker-centos7-ansible
    build: .
    hostname: schema-registry1.confluent
    container_name: schema-registry1
    privileged: true
    ports:
      - "8081:8081"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  control-center1:
    image: geerlingguy/docker-centos7-ansible
    hostname: control-center1.confluent
    container_name: control-center1
    privileged: true
    ports:
      - "9021:9021"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

volumes:
  supervisor-socket:
  rsyslog-socket:
  rsyslog-config:
